baseURL = "https://example.com/"
languageCode = "en-us"
title = "Pebble"
theme = "hugo-theme-pebble"
defaultContentLanguage = "en"
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[params.i18n]
defaultLang = "en"

[params.assets]
brandName = "iAssets"
logo = "/assets/logo.png"
logoAlt = "iAssets logo"
downloadQr = "/assets/qr-download.png"
version = "example-1"

[params.contact]
email = "hello@example.com"

[params.seo]
siteURL = "https://example.com"
defaultSocialTitle = "Pebble"

[params.pricing]
currency = "$"
yearly = "29"
lifetime = "99"

[params.copyright]
year = "2026"

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
identifier = "navFeatures"
url = "#features"
weight = 1

[[languages.en.menu.main]]
identifier = "navPricing"
url = "#pricing"
weight = 2

[[languages.en.menu.main]]
identifier = "navFaq"
url = "#faqs"
weight = 3

[[languages.en.menu.footer]]
identifier = "navTerms"
url = "/terms/"
weight = 1

[[languages.en.menu.footer]]
identifier = "navPrivacy"
url = "/privacy/"
weight = 2

[languages.zh]
languageName = "简体中文"
weight = 2

[[languages.zh.menu.main]]
identifier = "navFeatures"
url = "#features"
weight = 1

[[languages.zh.menu.main]]
identifier = "navPricing"
url = "#pricing"
weight = 2

[[languages.zh.menu.main]]
identifier = "navFaq"
url = "#faqs"
weight = 3

[[languages.zh.menu.footer]]
identifier = "navTerms"
url = "/terms/"
weight = 1

[[languages.zh.menu.footer]]
identifier = "navPrivacy"
url = "/privacy/"
weight = 2
